### ISSUE TITLE
Wifi and Bluetooth examples?

### ISSUE THREAD

**Issue by ruppde** [lakshanthad/Wio_Terminal_Classroom_Ardupy#2]
hi,

could you please publish examples on how to use wifi and bluetooth?

regards
arnim

**Comment by lakshanthad** [comment]
Hi,

Currently, WiFi and Bluetooth can only work with Arduino and not supported by ArduPy. WiFi and Bluetooth will be supported by ArduPy in the future. So, stay tuned!

Best Regards,
Lakshantha

**Comment by ruppde** [comment]
so you mean this statement from your webpage isn't true:

Compatible with Arduino and **Micropython**, Wio Terminal is an ATSAMD51-based microcontroller with **wireless connectivity** supported by Realtek RTL8720DN. https://www.seeedstudio.com/Wio-Terminal-p-4509.html

**Comment by lakshanthad** [comment]
Hi,
The webpage and the wiki pages are already updated and highlighted that Wio Terminal wireless connectivity is only supported by Arduino at the moment. Thank you for pointing it out.

We initially pointed out that ArduPy is also supported hoping to bring more functionalities later. Since ArduPy is quite new, we plan to gradually bring more functions in the future.

https://www.seeedstudio.com/Wio-Terminal-p-4509.html
https://wiki.seeedstudio.com/Wio-Terminal-Getting-Started/

Best Regards,
Lakshantha
